### ISSUE TITLE
.editorconfig or similar

### ISSUE THREAD

**Issue by webmanufaktur** [baumrock/RockFrontend#15]
Could you please add an .editorconfig file or something to define code formatting.
Otherwise submitting code changes could in a total reformatting-whitespace-disaster.

**Comment by BernhardBaumrock** [comment]
@gebeer do you know of an editorconfig that fits to our PSR12 coding style?

**Comment by gebeer** [comment]
> @gebeer do you know of an editorconfig that fits to our PSR12 coding style?

There is really not much that can be configured through editorconfig besides line endings and indentation. See https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties

I guess your question is aiming at the problem with hard to read PRs because of different coding styles. I think you could include a vscode workspace file in your projects that holds the PHP specific styling rules like in the file attached.

Also in the README you could ask contributors to adhere to certain standards, use certain vscode extensions etc. 
[example.code-workspace.txt](https://github.com/baumrock/RockFrontend/files/10201366/example.code-workspace.txt)

**Comment by BernhardBaumrock** [comment]
Thx @gebeer I took the easy route and copied the editorconfig file from RockMigrations to RockFrontend. Does that help @webmanufaktur ?
What I do to avoid code formatting messups in PRs for the core is to open files in atom editor that has no autoformatting at all and I simply take care of applying the same style as the original file has.
